x-app: &app
  env_file:
    - .env
    - .env.production
  build:
    context: .
    target: hyku-web
    cache_from:
      - ghcr.io/notch8/wvu_knapsack/base:latest
      - ghcr.io/notch8/wvu_knapsack:latest
    args:
      BUILDKIT_INLINE_CACHE: 1
      APP_PATH: ./hyrax-webapp
  image: ghcr.io/notch8/wvu_knapsack:${TAG:-latest}
  environment:
    # This line is what makes the knapsack include use the local code instead of the remote gem
    - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
    - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
    - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
  volumes:
    - ./data/node_modules:/app/samvera/hyrax-webapp/node_modules:cached
    - ./data/uploads:/app/samvera/hyrax-webapp/public/uploads:cached
    - ./data/assets:/app/samvera/hyrax-webapp/public/assets:cached
    - ./data/cache:/app/samvera/hyrax-webapp/tmp/cache:cached

networks:
  internal:

services:
  zoo:
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: zoo
    volumes:
      - ./data/zoo:/data
      - ./data/zk:/datalog

  solr:
    platform: linux/amd64
    image: ghcr.io/notch8/wvu_knapsack/solr:${TAG:-latest}
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: solr
    volumes:
      - ./data/solr:/var/solr

  fcrepo:
    env_file:
      - .env
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: fcrepo
    volumes:
      - ./data/fcrepo:/data

  db:
    env_file:
      - .env
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    image: ghcr.io/samvera/hyku/web:${TAG:-latest}
    env_file:
      - .env
      - .env.production
    environment:
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
      - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=.hyku.test
    volumes:
      - ./data/node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - ./data/uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - ./data/assets:/app/samvera/hyrax-webapp/public/assets:cached
      - ./data/cache:/app/samvera/hyrax-webapp/tmp/cache:cached
    networks:
      - internal
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      db:
        condition: service_started
      solr:
        condition: service_started
      fcrepo:
        condition: service_started
      redis:
        condition: service_started
      zoo:
        condition: service_started
      worker:
        condition: service_started
      initialize_app:
        condition: service_completed_successfully

  worker:
    image: ghcr.io/samvera/hyku/worker:${TAG:-latest}
    env_file:
      - .env
      - .env.production
    environment:
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
      - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
    volumes:
      - ./data/node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - ./data/uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - ./data/assets:/app/samvera/hyrax-webapp/public/assets:cached
      - ./data/cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera
    networks:
      - internal
    depends_on:
      initialize_app:
        condition: service_completed_successfully
      db:
        condition: service_started
      solr:
        condition: service_started
      fcrepo:
        condition: service_started
      redis:
        condition: service_started
      zoo:
        condition: service_started

  initialize_app:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: initialize_app

  redis:
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: redis
    volumes:
      - ./data/redis:/data
