x-app: &app
  env_file:
    - .env
    - .env.production
  build:
    context: .
    target: hyku-web
    cache_from:
      - ghcr.io/notch8/wvu_knapsack/base:latest
      - ghcr.io/notch8/wvu_knapsack:latest
    args:
      BUILDKIT_INLINE_CACHE: 1
      APP_PATH: ./hyrax-webapp
  image: ghcr.io/notch8/wvu_knapsack:${TAG:-latest}
  environment:
    # This line is what makes the knapsack include use the local code instead of the remote gem
    - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
    - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
    - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
  volumes:
    - ./data/node_modules:/app/samvera/hyrax-webapp/node_modules:cached
    - ./data/uploads:/app/samvera/hyrax-webapp/public/uploads:cached
    - ./data/assets:/app/samvera/hyrax-webapp/public/assets:cached
    - ./data/cache:/app/samvera/hyrax-webapp/tmp/cache:cached

networks:
  internal:

services:
  zoo:
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: zoo
    volumes:
      - ./data/zoo:/data
      - ./data/zk:/datalog

  solr:
    platform: linux/amd64
    image: ghcr.io/notch8/wvu_knapsack/solr:${TAG:-latest}
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: solr
    volumes:
      - ./data/solr:/var/solr

  fcrepo:
    env_file:
      - .env
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: fcrepo
    volumes:
      - ./data/fcrepo:/data

  db:
    platform: linux/amd64
    env_file:
      - .env
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: web
    # Uncomment command to access container with out starting bin/web. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    environment:
      # This line is what makes the knapsack include use the local code instead of the remote gem
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"

  worker:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: worker
    build:
      context: .
      target: hyku-worker
      cache_from:
        - ghcr.io/notch8/wvu_knapsack/base:latest
        - ghcr.io/notch8/wvu_knapsack/worker:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
        APP_PATH: ./hyrax-webapp
    image: ghcr.io/notch8/wvu_knapsack/worker:${TAG:-latest}
    # Uncomment command to access container with out starting bin/worker. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    volumes:
      - ./data/node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - ./data/uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - ./data/assets:/app/samvera/hyrax-webapp/public/assets:cached
      - ./data/cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera

  initialize_app:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: initialize_app

  redis:
    platform: linux/amd64
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: redis
    volumes:
      - ./data/redis:/data
